spring:
  datasource:
    url: jdbc:mysql://192.168.36.39:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Mysql@3306
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: com.qtbdp.quartz.demo.entity